name: Publish Keel.Domain.CleanCode

on:
  workflow_dispatch:
  push:
    tags:
      - "Keel.Domain.CleanCode-v*"

permissions:
  contents: read
  packages: write

jobs:
  publish_github_packages:
    uses: ./.github/workflows/publish-dotnet-package.yml
    with:
      project_path: src/Keel.Domain.CleanCode/Keel.Domain.CleanCode.csproj
    secrets: inherit

  publish_nugetorg:
    uses: ./.github/workflows/publish-nugetorg-package.yml
    with:
      project_path: src/Keel.Domain.CleanCode/Keel.Domain.CleanCode.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
