name: Publish Keel.Infra.RabbitMQ

on:
  workflow_dispatch:
  push:
    tags:
      - "Keel.Infra.RabbitMQ-v*"

permissions:
  contents: read
  packages: write

jobs:
  publish_github_packages:
    uses: ./.github/workflows/publish-dotnet-package.yml
    with:
      project_path: src/Keel.Infra.RabbitMQ/Keel.Infra.RabbitMQ.csproj
    secrets: inherit

  publish_nugetorg:
    uses: ./.github/workflows/publish-nugetorg-package.yml
    with:
      project_path: src/Keel.Infra.RabbitMQ/Keel.Infra.RabbitMQ.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
